// Your course packs, from Evia's own files, so Evia, Nisia, Milos and Paros all use the same topics:
//   - services/supabase/packs-seed.sql   the packs for Nisia (published, version by version)
//   - packages/core/courses.js           the copy Milos, Paros and the portal fall back on with no signal (was made by hand)
//   node tools/build-packs.mjs            (reads ../Evia7: app.js's course list, packs.js's topic ids, nvq-data.js, ksb-official.js)
// A pack is: its topics in order, each with a permanent id, its name, and the KSBs it covers in Evia's own short wording.
// The KSBs' full wording isn't in the pack: it's the standard's, from Nisia's library.
import fs from "node:fs"; import path from "node:path"; import vm from "node:vm"; import crypto from "node:crypto"; import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."), evia = path.resolve(root, "../Evia7");
const read = (f) => fs.readFileSync(path.join(evia, f), "utf8");

/* Evia's course list (app.js "const C={…}};"), topic ids (packs.js), the NVQ and the official KSB wording. */
const app = read("app.js"), start = app.indexOf("const C={"), end = app.indexOf("]}};", start) + 4;
if (start < 0 || end < 4) throw new Error("Couldn’t find Evia's course list in app.js");
const ctx = { window: {}, document: { scripts: [], head: { appendChild() {} } }, location: { href: "http://x/" } }; vm.createContext(ctx);
vm.runInContext(app.slice(start, end) + "\nwindow.C=C;", ctx, { filename: "app.js (courses)" });
vm.runInContext(read("packs.js"), ctx, { filename: "packs.js" });
for (const f of ["nvq-data.js", "ksb-official.js"]) vm.runInContext(read(f), ctx, { filename: f });
const C = ctx.window.C, P = ctx.window.eviaPacks, N = ctx.window.EVIA_NVQ, OFF = ctx.window.EVIA_KSB_OFFICIAL;

const split = (k) => { const i = String(k).indexOf("|"); return i < 0 ? { code: String(k), text: "" } : { code: k.slice(0, i), text: k.slice(i + 1) }; };
const order = (a, b) => "KSB".indexOf(a[0]) - "KSB".indexOf(b[0]) || +a.slice(1) - +b.slice(1);
const STD = { bricklayer: ["ST0095", "1.2", null], site: ["ST0264", "1.4", "site_carpenter"], joiner: ["ST0264", "1.4", "architectural_joiner"], trowel3: ["6570-05", "1.1", null] };
const VERSION = 1; /* bump to publish a new version of every pack */

const packs = {};
for (const course of ["bricklayer", "site", "joiner"]) {
  const c = C[course];
  packs[course] = { code: "nisia-" + course, course, title: c.name, standard: STD[course][0], version: STD[course][1], option: STD[course][2],
    topics: c.u.map(([name, ks]) => ({ id: P.unitId(course, name), name, ksbs: ks.map(split) })) };
}
/* The NVQ: its topics are the qualification's units, each covering all of its assessment criteria. */
packs.trowel3 = { code: "nisia-trowel3", course: "trowel3", title: "Trowel Occupations L3", standard: "6570-05", version: "1.1", option: null,
  topics: N.units.map((u) => ({ id: "trowel3/unit-" + u.n, name: u.n + " " + u.t, optional: !!u.opt, ksbs: u.o.flatMap((o) => o.c.map((c) => ({ code: u.n + "." + c.n, text: c.t }))) })) };

/* ---------- courses.js: the same shape Milos, Paros and the portal have always used ---------- */
const official = (course) => course === "bricklayer" ? OFF.bricklayer : course === "site" ? OFF.site : OFF.joiner;
const COURSE_DATA = {};
for (const [course, p] of Object.entries(packs)) {
  const units = p.topics.map((t) => course === "trowel3" ? [t.name, t.ksbs.map((k) => k.code), !!t.optional] : [t.name, t.ksbs.map((k) => k.code)]);
  if (course === "trowel3") {
    COURSE_DATA[course] = { name: p.title, std: "C&G 6570-05 NVQ L3", nvq: true, units, ksbs: p.topics.flatMap((t) => t.ksbs.map((k) => [k.code, k.text])), optional: p.topics.filter((t) => t.optional).map((t) => t.id.split("-").pop()) };
  } else {
    const O = official(course);
    COURSE_DATA[course] = { name: C[course].name, std: C[course].std, units, ksbs: Object.keys(O).sort((a, b) => a[0].localeCompare(b[0]) || +a.slice(1) - +b.slice(1)).map((k) => [k, O[k]]) };
  }
}
const out = path.join(root, "packages/core/courses.js");
fs.writeFileSync(out, "/* Each course's units and KSBs (NVQ: assessment criteria), taken from Evia's course packs. Generated by tools/build-packs.mjs: edit in Evia.\n" +
  "   Milos, Paros and the portal use the packs from Nisia (packages/core/packs.js); this is what they fall back on before the first download. */\nexport const COURSE_DATA=" + JSON.stringify(COURSE_DATA) + ";\n");

/* ---------- packs-seed.sql: the packs for Nisia ---------- */
const tag = (s) => { let t = "pk"; while (s.includes("$" + t + "$")) t += "x"; return "$" + t + "$"; };
let sql = "-- Your course packs, built by tools/build-packs.mjs from Evia's own files. Run after packs.sql.\n-- Safe to run again: a version already in Nisia is left as it is.\n";
for (const p of Object.values(packs)) {
  const content = { topics: p.topics }, j = JSON.stringify({ code: p.code, title: p.title, course: p.course, standard: p.standard, version: p.version, option: p.option, content }), t = tag(j);
  sql += `do $seed$ declare v uuid; begin
  if not exists (select 1 from public.course_pack_versions v join public.course_packs k on k.id = v.pack_id where k.code = '${p.code}' and v.version = ${VERSION}) then
    v := private.save_pack(${t}${j}${t}::jsonb, ${VERSION}, null);
    perform private.publish_pack(v);
  end if;
end $seed$;\n`;
}
sql += "-- Each course's pack: Evia's courses use yours.\n";
for (const p of Object.values(packs)) sql += `update public.courses c set pack_id = k.id from public.course_packs k where k.code = '${p.code}' and c.code in ('${p.course}'${p.course === "bricklayer" ? ", 'ST0095-v1.2-4bf187b9'" : ""}) and c.pack_id is null;\n`;
fs.writeFileSync(path.join(root, "services/supabase/packs-seed.sql"), sql);
const hash = (p) => crypto.createHash("sha256").update(JSON.stringify({ topics: p.topics })).digest("hex").slice(0, 12);
console.log("packs:", Object.values(packs).map((p) => p.code + " (" + p.topics.length + " topics, " + hash(p) + ")").join(", "));
