/* Copies Evia's per-unit "things to capture" and "things to mention", and the way Evia matches what's written against
   them, into packages/core/prompts.js, so Milos captures observations exactly as Evia captures evidence.
   Run from the repo root with Evia checked out beside it:  node tools/build-prompts.mjs ../Evia7 */
import fs from "node:fs"; import path from "node:path"; import vm from "node:vm";
const evia = process.argv[2] || "../Evia7";
const read = (f) => fs.readFileSync(path.join(evia, f), "utf8");
const between = (src, start, end) => { const i = src.indexOf(start); if (i < 0) throw new Error("Not found: " + start); const j = src.indexOf(end, i); return src.slice(i + start.length, j + end.length - 1); };
const prompts = vm.runInNewContext("(" + between(read("polish.js"), "const LEARNER_PROMPTS=", "\n  };") + ")");
const synSrc = between(read("ui.js"), "const SYNONYMS=", "\n  };");
vm.runInNewContext("(" + synSrc + ")");
/* The NVQ's evidence packs (one per real site job), from Evia's NVQ data. */
try {
  const win = {}; const ctx = vm.createContext({ window: win, document: { getElementById: () => null, querySelector: () => null, addEventListener() {} }, localStorage: { getItem: () => null, setItem() {} }, console });
  vm.runInContext(read("nvq-data.js"), ctx); vm.runInContext(read("nvq.js"), ctx);
  Object.assign(prompts, win.EVIA_EXTRA_PROMPTS || {});
  /* Which NVQ unit each job pack belongs to, so Milos can offer that unit's criteria at sign-off. */
  for (const m of read("nvq.js").matchAll(/\{unit:"(\d+)",sub:"[a-z]+",title:"([^"]+)"/g)) for (const c of Object.values(prompts)) if (c[m[2]] && c === prompts.trowel3) c[m[2]].unit = m[1];
} catch (e) { console.warn("NVQ packs not copied:", e.message); }
const out = "/* Generated by tools/build-prompts.mjs from Evia (polish.js, ui.js, nvq.js). Don't edit by hand. */\n" +
  "export const PROMPTS = " + JSON.stringify(prompts) + ";\n" +
  "export const SYNONYMS = " + synSrc + ";\n" +
  "export const split = (s) => String(s || \"\").split(\"·\").map((t) => t.trim()).filter(Boolean);\n" +
  "/* The same match Evia uses: a synonym, or every main word's stem. */\n" +
  "export function termMatched(term, text) {\n  text = String(text || \"\").toLowerCase();\n  return term.toLowerCase().split(\"/\").some((alt) => {\n    alt = alt.trim(); const syn = SYNONYMS[alt];\n    if (syn && syn.test(text)) return true;\n    const words = alt.replace(/&/g, \" \").split(/[^a-z0-9]+/).filter((w) => w.length >= 3 && ![\"and\", \"the\", \"for\", \"with\"].includes(w));\n    return words.length > 0 && words.every((w) => text.includes(/ions?$/.test(w) ? w.replace(/(at)?ions?$/, \"\").slice(0, 6) : w.replace(/s$/, \"\").slice(0, 5)));\n  });\n}\n";
fs.writeFileSync("packages/core/prompts.js", out);
console.log("Courses:", Object.keys(prompts).map((k) => k + " " + Object.keys(prompts[k]).length).join(", "));
